package com.colossus.product.dao;

import com.colossus.product.model.SkuSpec;

public interface SkuSpecMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_spec
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_spec
     *
     * @mbg.generated
     */
    int insert(SkuSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_spec
     *
     * @mbg.generated
     */
    int insertSelective(SkuSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_spec
     *
     * @mbg.generated
     */
    SkuSpec selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_spec
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SkuSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_spec
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SkuSpec record);
}