package com.colossus.product.dao;

import com.colossus.product.model.SkuSafeGuard;

public interface SkuSafeGuardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_safe_guard
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_safe_guard
     *
     * @mbg.generated
     */
    int insert(SkuSafeGuard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_safe_guard
     *
     * @mbg.generated
     */
    int insertSelective(SkuSafeGuard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_safe_guard
     *
     * @mbg.generated
     */
    SkuSafeGuard selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_safe_guard
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SkuSafeGuard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_safe_guard
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SkuSafeGuard record);
}