package com.colossus.product.dao;

import com.colossus.product.model.SpecValue;

public interface SpecValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_value
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_value
     *
     * @mbg.generated
     */
    int insert(SpecValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_value
     *
     * @mbg.generated
     */
    int insertSelective(SpecValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_value
     *
     * @mbg.generated
     */
    SpecValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SpecValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SpecValue record);
}