package com.colossus.product.dao;

import com.colossus.product.model.SpuSpec;

public interface SpuSpecMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_spec
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_spec
     *
     * @mbg.generated
     */
    int insert(SpuSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_spec
     *
     * @mbg.generated
     */
    int insertSelective(SpuSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_spec
     *
     * @mbg.generated
     */
    SpuSpec selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_spec
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SpuSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_spec
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SpuSpec record);
}